
export type Genre = 'Sandbox' | 'Survival' | 'Action' | 'RPG' | 'Strategy';

export interface Skill {
  id: string;
  name: string;
  category: 'Communication' | 'Creative Problem Solving' | 'Self-Management' | 'Collaboration';
  color: string;
  activeColor: string;
  icon: string;
}

export const SKILLS: Skill[] = [
  { id: 'listening', name: 'Listening', category: 'Communication', color: '#F8BBD0', activeColor: '#E91E63', icon: 'Ear' },
  { id: 'speaking', name: 'Speaking', category: 'Communication', color: '#FFCDD2', activeColor: '#F44336', icon: 'MessageSquare' },
  { id: 'problem-solving', name: 'Problem Solving', category: 'Creative Problem Solving', color: '#FFE0B2', activeColor: '#FF9800', icon: 'Puzzle' },
  { id: 'creativity', name: 'Creativity', category: 'Creative Problem Solving', color: '#FFF9C4', activeColor: '#FFC107', icon: 'Lightbulb' },
  { id: 'adapting', name: 'Adapting', category: 'Self-Management', color: '#DCEDC8', activeColor: '#8BC34A', icon: 'RefreshCw' },
  { id: 'planning', name: 'Planning', category: 'Self-Management', color: '#C8E6C9', activeColor: '#4CAF50', icon: 'Calendar' },
  { id: 'leadership', name: 'Leadership', category: 'Collaboration', color: '#B2EBF2', activeColor: '#00BCD4', icon: 'Users' },
  { id: 'teamwork', name: 'Teamwork', category: 'Collaboration', color: '#BBDEFB', activeColor: '#2196F3', icon: 'Handshake' },
];

export const GENRES: Genre[] = ['Sandbox', 'Survival', 'Action', 'RPG', 'Strategy'];

export const SKILL_STEP_DESCRIPTORS: Record<string, Record<number, string>> = {
  listening: {
    1: "I can listen for at least a short time.",
    2: "I remember simple instructions.",
    3: "I ask questions if I don't understand.",
    4: "I pass on information accurately.",
    5: "I know why someone is communicating with me.",
    6: "I record important information.",
    7: "I show I am paying attention.",
    8: "I ask open questions to understand more.",
    9: "I rephrase or summarise what I learnt.",
    10: "I recognise tone of communication.",
    11: "I recognise when someone is trying to influence me.",
    12: "I compare different points of view.",
    13: "I explore why different views might come about.",
    14: "I analyse where bias is shown.",
    15: "I use questions to challenge perspectives.",
    16: "I objectively evaluate and integrate different perspectives."
  },
  speaking: {
    1: "I communicate clearly with someone I know.",
    2: "I communicate clearly in a small group.",
    3: "I communicate with new people when I need to.",
    4: "I order my points to be understood.",
    5: "I adapt my communication to what my audience already know.",
    6: "I choose appropriate language for the situation.",
    7: "I use tone, expression and gesture to be understood.",
    8: "I use facts and examples to support my communication.",
    9: "I use images, charts or diagrams when it helps my communication.",
    10: "I talk about difficult or sensitive topics effectively.",
    11: "I communicate in a way that is engaging for my audience.",
    12: "I adapt my communication depending on audience reactions.",
    13: "I manage discussions effectively to reach an agreement.",
    14: "I maintain clear and constructive communication in challenging situations.",
    15: "I present to an audience when required.",
    16: "I communicate a vision persuasively."
  },
  'problem-solving': {
    1: "I follow instructions.",
    2: "I find help from someone if needed.",
    3: "I describe problems to others.",
    4: "I find information to complete a task.",
    5: "I create different possible solutions to a problem.",
    6: "I identify advantages and disadvantages of potential solutions.",
    7: "I choose between possible solutions based on success criteria.",
    8: "I research to build my understanding.",
    9: "I analyse causes and effects.",
    10: "I identify patterns to gain insight.",
    11: "I identify how parts of a system impact each other.",
    12: "I use logical reasoning to structure problems.",
    13: "I structure ideas so that I can test them.",
    14: "I develop strategic plans to address complex problems.",
    15: "I evaluate the success of strategic plans.",
    16: "I improve strategic plans based on new insights."
  },
  creativity: {
    1: "Imagining: I imagine different things.",
    2: "Sharing imagination: I share what I imagine with someone.",
    3: "Expressing imagination: I share what I imagine in different ways.",
    4: "Generating ideas: I create ideas to solve a problem.",
    5: "Suggesting improvements: I create ideas to make something better.",
    6: "Combining concepts: I can combine ideas to make new ones.",
    7: "Identifying opportunities: I identify opportunities for innovation.",
    8: "Defining success: I set out success criteria for creating new ideas.",
    9: "Flexible thinking: I challenge my assumptions about ideas.",
    10: "Reflecting critically: I question my own ideas to improve them.",
    11: "Seeking perspectives: I seek different perspectives to develop my ideas.",
    12: "Prototyping: I create quick tests of an idea.",
    13: "Incubating ideas: I give ideas time and attention to evolve.",
    14: "Using curiosity: I seek new concepts and ideas to innovate from.",
    15: "Facilitating creativity: I share creative tools for collective innovation.",
    16: "Championing creativity: I nurture cultures of creativity and innovation."
  },
  adapting: {
    1: "Identifying feelings: I can tell how I am feeling.",
    2: "Recognising feelings: I can tell how others are feeling.",
    3: "Persisting: I keep going when faced with challenges.",
    4: "Managing reactions: I respond calmly when faced with challenges.",
    5: "Reflecting: I reflect and learn from challenges.",
    6: "Supporting others: I help others face challenges.",
    7: "Encouraging others: I encourage others to keep going.",
    8: "Managing wellbeing: I have routines to manage my wellbeing.",
    9: "Managing workload: I manage my workload effectively.",
    10: "Seeking growth: I seek opportunities to grow my experience.",
    11: "Looking for opportunities: I look for opportunities when faced with challenges.",
    12: "Helping others see opportunities: I help others see opportunities.",
    13: "Adapting plans: I change plans to work through setbacks.",
    14: "Identifying risk: I identify potential risks and gains.",
    15: "Managing risk: I actively manage risks.",
    16: "Being enterprising: I capitalise on opportunities."
  },
  planning: {
    1: "Sensing difficulty: I know when something is too difficult.",
    2: "Identifying success: I know what doing well looks like for me.",
    3: "Working carefully: I work with care and attention.",
    4: "Recognising strengths: I recognise what I am good at.",
    5: "Facing challenges: I take a positive approach to new challenges.",
    6: "Setting goals: I set achievable goals for myself.",
    7: "Thinking ahead: I think about routes to achieve a goal.",
    8: "Prioritising: I order and prioritise tasks to achieve goals.",
    9: "Resourcing: I secure the resources I need to achieve goals.",
    10: "Involving others: I engage others to achieve goals.",
    11: "Using skills: I plan how to use and build my skills to achieve goals.",
    12: "Target setting: I create plans with clear targets to measure success.",
    13: "Seeking feedback: I seek out a range of views to improve plans.",
    14: "Project planning: I use planning tools to organise complex projects.",
    15: "Adaptive planning: I use data to evaluate progress and make adaptations.",
    16: "Agile planning: I work flexibly and responsively to improve my plans."
  },
  leadership: {
    1: "Identifying feelings: I can tell how I am feeling.",
    2: "Recognising feelings: I can tell how others are feeling.",
    3: "Speaking clearly: I explain how an idea makes me feel.",
    4: "Dividing tasks: I can divide up tasks in a fair way.",
    5: "Resource management: I can manage resources to get a task done.",
    6: "Supporting others: I use my experience to support others.",
    7: "Recognising reactions: I recognise when others have strong feelings.",
    8: "Managing feelings: I can help others to stay positive.",
    9: "Reflecting on leadership: I can identify my own leadership strengths.",
    10: "Recognising strengths: I identify others' strengths.",
    11: "Motivating others: I motivate others by how I communicate.",
    12: "Providing feedback: I give feedback that helps others to improve.",
    13: "Managing discussions: I manage discussions to reach an agreement.",
    14: "Strategic leadership: I develop strategic plans for others to follow.",
    15: "Evaluating leadership: I evaluate the success of my leadership.",
    16: "Adaptive leadership: I adapt my leadership to different situations."
  },
  teamwork: {
    1: "Working with others: I work with others in a positive way.",
    2: "Following rules: I follow the rules of the group.",
    3: "Being reliable: I am reliable in my work.",
    4: "Taking responsibility: I take responsibility for my work.",
    5: "Helping others: I help others when they need it.",
    6: "Seeking help: I seek help when I need it.",
    7: "Recognising value: I recognise the value of others' ideas.",
    8: "Valuing others: I show I value others’ ideas.",
    9: "Analysing team tasks: I can identify the different tasks in a team.",
    10: "Reviewing team tasks: I check how team tasks are going.",
    11: "Contributing to team goals: I contribute to the team's success.",
    12: "Evaluating team goals: I evaluate the team's progress.",
    13: "Negotiating: I negotiate to resolve conflicts.",
    14: "Managing conflict: I can manage conflict in a team.",
    15: "Evaluating teamwork: I evaluate how well the team worked together.",
    16: "Developing teamwork: I help the team to work together better."
  }
};

// This is a sample library. In a real app, this would be a full 640-entry matrix.
// For the demo, we'll provide a fallback generator if the specific entry is missing.
export const CATALYST_TASKS: Record<string, string> = {
  // Listening - Sandbox
  'Sandbox-listening-1': "Follow a single, 1-step build instruction.",
  'Sandbox-listening-2': "Recall a 2-item material list without reminders.",
  'Sandbox-listening-3': "Ask for a demo of a specific build technique.",
  'Sandbox-listening-4': "Retell a shared build plan to another peer.",
  'Sandbox-listening-5': "Distinguish between a \"tip\" and a direct \"order\".",
  'Sandbox-listening-6': "Write down a \"To-Do\" list using in-game signs.",
  'Sandbox-listening-7': "Use character gestures to confirm focus on a brief.",
  'Sandbox-listening-8': "Ask: \"How can we make this project better?\".",
  'Sandbox-listening-9': "Summarise the agreed build rules for the session.",
  'Sandbox-listening-10': "Identify if a peer's suggestion is hesitant or unsure.",
  'Sandbox-listening-11': "Identify if a peer is trying to \"take over\" a build.",
  'Sandbox-listening-12': "Compare two different layout ideas for a village.",
  'Sandbox-listening-13': "Discuss \"Survival\" needs versus \"Creative\" wants.",
  'Sandbox-listening-14': "Spot a mentor's bias for a specific colour or style.",
  'Sandbox-listening-15': "Challenge a build's structural logic with \"What if\" questions.",
  'Sandbox-listening-16': "Build a \"Hybrid Style\" project from multiple ideas.",

  // Listening - Survival
  'Survival-listening-1': "Listen for a specific environmental sound cue.",
  'Survival-listening-2': "Remember a 2-ingredient crafting recipe.",
  'Survival-listening-3': "Ask for clarification on a survival mechanic.",
  'Survival-listening-4': "Report scouted resource locations to the team.",
  'Survival-listening-5': "Identify a \"warning\" call-out versus a \"social\" chat.",
  'Survival-listening-6': "Note down a specific rare monster spawn time.",
  'Survival-listening-7': "Maintain focus during a complex raid briefing.",
  'Survival-listening-8': "Ask: \"What happens if we explore at night?\".",
  'Survival-listening-9': "Summarise the extraction or escape plan.",
  'Survival-listening-10': "Recognise \"panic\" in a teammate's voice during a crisis.",
  'Survival-listening-11': "Recognise a \"dare\" to do something dangerous.",
  'Survival-listening-12': "Compare two different base locations for survival.",
  'Survival-listening-13': "Analyse why a teammate fears a specific zone.",
  'Survival-listening-14': "Identify if a \"Wiki\" is biased toward \"pro-play\".",
  'Survival-listening-15': "Challenge a risky trek by asking for risk assessments.",
  'Survival-listening-16': "Create a plan that suits all team experience levels.",

  // Listening - Action
  'Action-listening-1': "React to a single verbal \"Go\" or \"Start\" signal.",
  'Action-listening-2': "Recall a specific button combo sequence.",
  'Action-listening-3': "Ask how a specific power-up or tool works.",
  'Action-listening-4': "Call out enemy positions accurately.",
  'Action-listening-5': "Differentiate tactical \"pings\" from social banter.",
  'Action-listening-6': "Record an opponent's ability cooldown time.",
  'Action-listening-7': "Provide verbal \"Ready\" cues to confirm understanding.",
  'Action-listening-8': "Ask: \"Why are we using this specific loadout?\".",
  'Action-listening-9': "Rephrase the boss-fight strategy to the team.",
  'Action-listening-10': "Detect \"frustration\" in a rival's chat message.",
  'Action-listening-11': "Identify \"baiting\" by an enemy player or team.",
  'Action-listening-12': "Compare two tactical retreat or push routes.",
  'Action-listening-13': "Explore why teams use different strategic metas.",
  'Action-listening-14': "Analyse bias in community \"Tier Lists\" for gear.",
  'Action-listening-15': "Question the necessity of a specific fight or move.",
  'Action-listening-16': "Synthesise a tactic using input from all players.",

  // Listening - RPG
  'RPG-listening-1': "Follow one direct NPC instruction.",
  'RPG-listening-2': "Remember a character's name or title.",
  'RPG-listening-3': "Ask for a repeat of a quest objective.",
  'RPG-listening-4': "Summarise a plot point for the mentor.",
  'RPG-listening-5': "Identify if an NPC is helpful, neutral, or hostile.",
  'RPG-listening-6': "Log a specific code or riddle answer found in text.",
  'RPG-listening-7': "Use active listening cues during long dialogue.",
  'RPG-listening-8': "Ask: \"What motivated that character's choice?\".",
  'RPG-listening-9': "Summarise the quest lore or history.",
  'RPG-listening-10': "Identify a sarcastic or mocking NPC response.",
  'RPG-listening-11': "Spot a \"deceptive\" attempt by a story NPC.",
  'RPG-listening-12': "Compare two conflicting quest choices.",
  'RPG-listening-13': "Analyse a character's conflicting motivations.",
  'RPG-listening-14': "Identify a biased narrator in the game's story.",
  'RPG-listening-15': "Probe an NPC's \"Plan B\" with targeted questions.",
  'RPG-listening-16': "Solve a mystery using all collected clues and lore.",

  // Listening - Strategy
  'Strategy-listening-1': "Execute one unit movement command.",
  'Strategy-listening-2': "Recall the primary win condition.",
  'Strategy-listening-3': "Ask for clarification on a unit statistic.",
  'Strategy-listening-4': "Explain the map state to a teammate.",
  'Strategy-listening-5': "Identify if a signal is for help or an attack.",
  'Strategy-listening-6': "Track the enemy's resource or gold count.",
  'Strategy-listening-7': "Acknowledge a strategic shift immediately.",
  'Strategy-listening-8': "Ask: \"How will this move affect our defence?\".",
  'Strategy-listening-9': "Rephrase the terms of a shared alliance.",
  'Strategy-listening-10': "Detect \"confidence\" or \"bluffing\" in a proposed plan.",
  'Strategy-listening-11': "Recognise \"propaganda\" from a specific faction.",
  'Strategy-listening-12': "Compare two different opening gambits or starts.",
  'Strategy-listening-13': "Explore why an opponent chose a specific tree.",
  'Strategy-listening-14': "Spot bias in a \"Balance Patch\" or community update.",
  'Strategy-listening-15': "Challenge a move by asking about potential counters.",
  'Strategy-listening-16': "Create a strategy using all available scout data.",
  
  // Problem Solving - Sandbox
  'Sandbox-problem-solving-1': "Build a specific structure by following a mentor's step-by-step guide.",
  'Sandbox-problem-solving-2': "Ask a peer how to use a specific material or logic component.",
  'Sandbox-problem-solving-3': "Explain why a build isn't working (e.g. \"The roof keeps collapsing\").",
  'Sandbox-problem-solving-4': "Look up a \"build guide\" to see the dimensions needed for a project.",
  'Sandbox-problem-solving-5': "Suggest three different ways to light up a dark room.",
  'Sandbox-problem-solving-6': "Discuss the pros/cons of using wood vs. stone for a large build.",
  'Sandbox-problem-solving-7': "Pick a material based on what is currently \"in stock\" and easy to find.",
  'Sandbox-problem-solving-8': "Watch a video on \"advanced lighting\" to improve a build's atmosphere.",
  'Sandbox-problem-solving-9': "Identify that \"too many mobs\" are spawning because the area lacks light.",
  'Sandbox-problem-solving-10': "Notice that the \"village\" grows faster when paths are laid out first.",
  'Sandbox-problem-solving-11': "Explain how a logic \"clock\" impacts the speed of a farm.",
  'Sandbox-problem-solving-12': "Create a \"Flow Chart\" for a complex auto-sorter build.",
  'Sandbox-problem-solving-13': "Create two \"test patches\" of roofs to see which looks better.",
  'Sandbox-problem-solving-14': "Develop a plan for a \"Mega-Build\" that involves 5 different stages.",
  'Sandbox-problem-solving-15': "Review a finished build to see if it met the \"initial vision\".",
  'Sandbox-problem-solving-16': "Redesign a \"City Layout\" based on how players actually move through it.",

  // Problem Solving - Survival
  'Survival-problem-solving-1': "Craft a basic tool by following the in-game recipe exactly.",
  'Survival-problem-solving-2': "Request a \"rescue\" or help with resource gathering when stuck.",
  'Survival-problem-solving-3': "Describe a survival threat to the team (e.g. \"The fire is out\").",
  'Survival-problem-solving-4': "Check the in-game \"compendium\" to find where a resource spawns.",
  'Survival-problem-solving-5': "Propose two different ways to stay warm during a blizzard.",
  'Survival-problem-solving-6': "Compare the risk of hunting at night vs. the reward of rare loot.",
  'Survival-problem-solving-7': "Choose a base location based on proximity to water and fuel.",
  'Survival-problem-solving-8': "Read a wiki to understand \"spawn mechanics\" for rare resources.",
  'Survival-problem-solving-9': "Recognise that the \"base took damage\" because a wall was left open.",
  'Survival-problem-solving-10': "Identify the \"attack pattern\" of a monster to time your dodges.",
  'Survival-problem-solving-11': "Explain how \"encumbrance\" impacts the ability to outrun predators.",
  'Survival-problem-solving-12': "Structure a \"Tiered Defence\" plan for a base raid.",
  'Survival-problem-solving-13': "Run a \"1-day trial\" of a new resource-gathering route to check yield.",
  'Survival-problem-solving-14': "Create a \"Season Plan\" for base expansion, farming, and exploration.",
  'Survival-problem-solving-15': "Analyse a \"Base Raid\" to see what held up and what broke down.",
  'Survival-problem-solving-16': "Adapt \"Base Defence\" based on the new enemies found in late-game.",

  // Problem Solving - Action
  'Action-problem-solving-1': "Navigate to a specific map coordinate as directed by the squad leader.",
  'Action-problem-solving-2': "Ask a teammate for a specific weapon or health item when depleted.",
  'Action-problem-solving-3': "Identify a tactical issue (e.g. \"We are pinned down by a sniper\").",
  'Action-problem-solving-4': "Research a specific weapon's \"stats\" to see its effective range.",
  'Action-problem-solving-5': "Suggest two different ways to enter a guarded building.",
  'Action-problem-solving-6': "Evaluate the speed of a car vs. the stealth of walking to the next zone.",
  'Action-problem-solving-7': "Select a weapon based on the final circle being in an open field.",
  'Action-problem-solving-8': "Use a \"training mode\" to research the recoil patterns of different guns.",
  'Action-problem-solving-9': "Analyse that \"we lost the fight\" because the team was too far apart.",
  'Action-problem-solving-10': "Recognise that the \"storm\" consistently moves toward a terrain type.",
  'Action-problem-solving-11': "Describe how \"weapon rarity\" impacts the time-to-kill in a match.",
  'Action-problem-solving-12': "Create a \"Decision Tree\" for when to engage vs. when to run away.",
  'Action-problem-solving-13': "Test a new \"sensitivity setting\" in a practice match to check aim.",
  'Action-problem-solving-14': "Design a \"Tournament Strategy\" for a series of competitive matches.",
  'Action-problem-solving-15': "Review a match recording to identify where the strategy failed.",
  'Action-problem-solving-16': "Adjust \"Squad Rotation\" based on the latest game \"balance patch\".",

  // Problem Solving - RPG
  'RPG-problem-solving-1': "Complete a tutorial quest by following the on-screen prompts.",
  'RPG-problem-solving-2': "Ask the mentor for a hint on where to find a specific quest item.",
  'RPG-problem-solving-3': "Detail a quest roadblock (e.g. \"The NPC won't talk to me\").",
  'RPG-problem-solving-4': "Use the quest log to find the specific location mentioned in dialogue.",
  'RPG-problem-solving-5': "Create a list of three different \"loadouts\" to use against a boss.",
  'RPG-problem-solving-6': "Weigh up the benefits of \"Strength\" vs. \"Dexterity\" gear for a fight.",
  'RPG-problem-solving-7': "Select a character \"skill\" based on the specific resistances of a boss.",
  'RPG-problem-solving-8': "Research the \"lore\" of a character to find a clue for a secret.",
  'RPG-problem-solving-9': "Identify that \"the quest failed\" because an NPC was hit.",
  'RPG-problem-solving-10': "Identify a recurring \"clue\" type used in the game's secret puzzles.",
  'RPG-problem-solving-11': "Identify how \"Stat Scaling\" impacts damage output as you level up.",
  'RPG-problem-solving-12': "Structure a \"Build Guide\" that follows a specific logical progression.",
  'RPG-problem-solving-13': "Test a \"new weapon\" on a weak enemy to see damage predictions.",
  'RPG-problem-solving-14': "Develop a \"100% Completion Plan\" for all quests and secrets.",
  'RPG-problem-solving-15': "Evaluate if a \"Character Build\" was as effective as hoped in late-game.",
  'RPG-problem-solving-16': "Respec a \"Character\" to fix weaknesses found during a boss fight.",

  // Problem Solving - Strategy
  'Strategy-problem-solving-1': "Execute a specific unit movement as outlined in the opening tutorial.",
  'Strategy-problem-solving-2': "Ask a teammate to explain a specific building or unit statistic.",
  'Strategy-problem-solving-3': "Identify a strategic weakness (e.g. \"Our gold income is too low\").",
  'Strategy-problem-solving-4': "Use the help menu to understand a specific unit counter.",
  'Strategy-problem-solving-5': "Propose three different opening moves for a new match.",
  'Strategy-problem-solving-6': "Analyse the cost of a large army vs. the benefit of faster research.",
  'Strategy-problem-solving-7': "Choose a \"Civic\" or \"Tech\" based on the shared victory goal.",
  'Strategy-problem-solving-8': "Study \"meta\" strategies to understand high-level opening moves.",
  'Strategy-problem-solving-9': "Identify that \"production slowed\" because a resource was cut off.",
  'Strategy-problem-solving-10': "Recognise an opponent's \"opening pattern\" to predict their mid-game.",
  'Strategy-problem-solving-11': "Analyse how \"Luxury Resources\" impact city happiness and growth.",
  'Strategy-problem-solving-12': "Create a \"Strategic Roadmap\" for a 50-turn victory plan.",
  'Strategy-problem-solving-13': "Test a \"new opening\" in a match against an AI to check viability.",
  'Strategy-problem-solving-14': "Design a \"Full Campaign Strategy\" for multiple opponents.",
  'Strategy-problem-solving-15': "Review a \"Victory Screen\" to see which strategic metrics were highest.",
  'Strategy-problem-solving-16': "Refine a \"Speed-Run\" strategy based on time-save discoveries.",

  // Speaking - Sandbox
  'Sandbox-speaking-1': "Describe a single block or item you have placed.",
  'Sandbox-speaking-2': "Explain a simple build idea to the team.",
  'Sandbox-speaking-3': "Ask a new player if they would like to help with a project.",
  'Sandbox-speaking-4': "Explain the steps of a build in the correct order.",
  'Sandbox-speaking-5': "Explain a complex build to a beginner without using jargon.",
  'Sandbox-speaking-6': "Use architectural terms when discussing a formal project.",
  'Sandbox-speaking-7': "Use character emotes to emphasise a build point.",
  'Sandbox-speaking-8': "Use block counts or dimensions to justify a design choice.",
  'Sandbox-speaking-9': "Draw a simple floor plan on a sign to show a build.",
  'Sandbox-speaking-10': "Discuss accidental damage to a build with a peer calmly.",
  'Sandbox-speaking-11': "Present a finished build with a descriptive story.",
  'Sandbox-speaking-12': "Change your build pitch if the mentor looks uninterested.",
  'Sandbox-speaking-13': "Facilitate a vote on which theme a build should follow.",
  'Sandbox-speaking-14': "Stay on-task and helpful even if a build project fails.",
  'Sandbox-speaking-15': "Give a formal presentation of a world to visitors.",
  'Sandbox-speaking-16': "Inspire a group to spend weeks on a mega-build project.",

  // Speaking - Survival
  'Survival-speaking-1': "State which basic resource you are currently gathering.",
  'Survival-speaking-2': "State your current health or hunger status to the group.",
  'Survival-speaking-3': "Trade resources with a player you haven't met before.",
  'Survival-speaking-4': "Explain a crafting process from raw material to finished tool.",
  'Survival-speaking-5': "Warn a new player about a danger they haven't seen yet.",
  'Survival-speaking-6': "Use tactical language during a high-pressure encounter.",
  'Survival-speaking-7': "Use voice tone to convey the urgency of a resource shortage.",
  'Survival-speaking-8': "Use stat comparisons to explain why an armour set is better.",
  'Survival-speaking-9': "Use an inventory screenshot to show what is missing.",
  'Survival-speaking-10': "Discuss the loss of items after a wipe without blame.",
  'Survival-speaking-11': "Tell a \"survival story\" of a narrow escape to the group.",
  'Survival-speaking-12': "Slow down an explanation if a peer is struggling.",
  'Survival-speaking-13': "Mediate a disagreement over a permanent base location.",
  'Survival-speaking-14': "Maintain calm leadership while a base is under attack.",
  'Survival-speaking-15': "Lead a new player orientation for server rules.",
  'Survival-speaking-16': "Persuade a team to attempt a hard-core survival challenge.",

  // Speaking - Action
  'Action-speaking-1': "Call out when you have found a weapon or shield.",
  'Action-speaking-2': "Call out an enemy's compass direction to teammates.",
  'Action-speaking-3': "Use voice chat to coordinate with a random teammate.",
  'Action-speaking-4': "Brief the team on a three-part tactical plan.",
  'Action-speaking-5': "Explain a game mechanic to a teammate new to the genre.",
  'Action-speaking-6': "Keep call-outs short and relevant during intense combat.",
  'Action-speaking-7': "Use clear, confident vocal commands to lead a push.",
  'Action-speaking-8': "Use damage numbers or cooldowns to justify a weapon choice.",
  'Action-speaking-9': "Use map markers to illustrate a complex rotation route.",
  'Action-speaking-10': "Provide constructive feedback after a failed match.",
  'Action-speaking-11': "Give an exciting commentary while spectating a teammate.",
  'Action-speaking-12': "Pivot tactical call-outs if the team sounds overwhelmed.",
  'Action-speaking-13': "Lead a post-match discussion to agree on next strategy.",
  'Action-speaking-14': "Keep giving clear call-outs even when you are the only player left alive.",
  'Action-speaking-15': "Deliver a squad briefing before a competitive match.",
  'Action-speaking-16': "Motivate a squad to believe they can win a hard fight.",

  // Speaking - RPG
  'RPG-speaking-1': "State which NPC you are currently talking to.",
  'RPG-speaking-2': "Share a quest objective with the party.",
  'RPG-speaking-3': "Introduce your character to a new player in a hub area.",
  'RPG-speaking-4': "Summarise a quest's backstory in a logical sequence.",
  'RPG-speaking-5': "Summarise the \"Main Quest\" for a mentor who missed it.",
  'RPG-speaking-6': "Use in-character language that fits the game setting.",
  'RPG-speaking-7': "Roleplay character emotions (e.g. worry) using your voice.",
  'RPG-speaking-8': "Cite quest log entries to prove a specific plot point.",
  'RPG-speaking-9': "Share a skill tree screenshot to explain character progress.",
  'RPG-speaking-10': "Discuss a moral dilemma presented in the game story.",
  'RPG-speaking-11': "Narrate your character's journey as if it were an epic legend.",
  'RPG-speaking-12': "Alter in-character dialogue if others aren't roleplaying.",
  'RPG-speaking-13': "Negotiate with a group to decide which faction to support.",
  'RPG-speaking-14': "Stay in character even during high-stakes story moments.",
  'RPG-speaking-15': "Perform a lore summary for the party before a major event.",
  'RPG-speaking-16': "Pitch an original storyline or campaign to other players.",

  // Speaking - Strategy
  'Strategy-speaking-1': "State which unit or building you are selecting.",
  'Strategy-speaking-2': "Inform the team which territory you are moving into.",
  'Strategy-speaking-3': "Negotiate a temporary alliance with a new opponent.",
  'Strategy-speaking-4': "Outline the phases of your next three turns.",
  'Strategy-speaking-5': "Explain a move focusing only on the new information.",
  'Strategy-speaking-6': "Use formal diplomatic language when negotiating a treaty.",
  'Strategy-speaking-7': "Use a calm tone to reassure a teammate during a loss.",
  'Strategy-speaking-8': "Use resource yield data to justify a settlement location.",
  'Strategy-speaking-9': "Use the tech tree UI to show the team the long-term research path.",
  'Strategy-speaking-10': "Address a broken alliance in a professional manner.",
  'Strategy-speaking-11': "Pitch a bold strategy to the team to get them excited.",
  'Strategy-speaking-12': "Re-explain a strategy using different examples if challenged.",
  'Strategy-speaking-13': "Manage a multi-player discussion on victory conditions.",
  'Strategy-speaking-14': "Maintain professionalism during a long stalemate or loss.",
  'Strategy-speaking-15': "Present a strategic overview of the map state to a council.",
  'Strategy-speaking-16': "Persuade an alliance to follow a high-risk victory plan.",

  // Creativity - Sandbox
  'Sandbox-creativity-1': "Imagine a futuristic version of a standard medieval house.",
  'Sandbox-creativity-2': "Describe your futuristic house idea to the mentor.",
  'Sandbox-creativity-3': "Use a variety of blocks to \"sketch\" a 3D model of your idea.",
  'Sandbox-creativity-4': "Create a creative way to hide a door using hidden switches.",
  'Sandbox-creativity-5': "Suggest three creative ways to improve the village lighting.",
  'Sandbox-creativity-6': "Combine Gothic and Modern styles into one build.",
  'Sandbox-creativity-7': "Spot a gap in the build and suggest an original feature.",
  'Sandbox-creativity-8': "Define what makes an original build (e.g. no tutorials).",
  'Sandbox-creativity-9': "Question if a house must have a roof or traditional walls.",
  'Sandbox-creativity-10': "Self-critique your build: \"Is this too busy? How do I fix it?\".",
  'Sandbox-creativity-11': "Ask three players: \"What would you add to this garden?\".",
  'Sandbox-creativity-12': "Build a palette of three blocks to see if they match.",
  'Sandbox-creativity-13': "Work on a complex build over three sessions without rushing.",
  'Sandbox-creativity-14': "Look at real-world architecture to inspire an in-game build.",
  'Sandbox-creativity-15': "Teach the team how to use a specific building hack.",
  'Sandbox-creativity-16': "Start a creative challenge where everyone builds weekly.",

  // Creativity - Survival
  'Survival-creativity-1': "Imagine a secret base hidden inside a natural landmark.",
  'Survival-creativity-2': "Sketch or describe your hidden base layout to a peer.",
  'Survival-creativity-3': "Use in-game signs or a map to outline the base perimeter.",
  'Survival-creativity-4': "Invent a creative trap to stop monsters from entering.",
  'Survival-creativity-5': "Design a more creative way to organise the storage room.",
  'Survival-creativity-6': "Combine a treehouse with a waterfall to make a base.",
  'Survival-creativity-7': "Identify a game mechanic that could be used for building.",
  'Survival-creativity-8': "Set rules for a survival-friendly creative build.",
  'Survival-creativity-9': "Challenge the idea that bases must be stationary.",
  'Survival-creativity-10': "Review your base defence: \"Where would I attack this?\".",
  'Survival-creativity-11': "Ask the mentor: \"How would you hide this entrance?\".",
  'Survival-creativity-12': "Try building a small section of a wall to test the look.",
  'Survival-creativity-13': "Let a base design grow as you find more materials.",
  'Survival-creativity-14': "Research how other cultures survived to inspire a base.",
  'Survival-creativity-15': "Share a blueprint tool to help others build creatively.",
  'Survival-creativity-16': "Encourage the server to ignore meta and build for fun.",

  // Creativity - Action
  'Action-creativity-1': "Imagine a unique victory dance or celebration sequence.",
  'Action-creativity-2': "Tell your squad about your celebration idea.",
  'Action-creativity-3': "Use emotes and character movements to demonstrate your idea.",
  'Action-creativity-4': "Design a creative distraction to lure enemies away.",
  'Action-creativity-5': "Suggest a creative tweak to the team's standard uniform.",
  'Action-creativity-6': "Combine two different weapon types into a new strategy.",
  'Action-creativity-7': "Spot a terrain feature that allows for a new tactic.",
  'Action-creativity-8': "Define what a successful creative play looks like.",
  'Action-creativity-9': "Question the meta weapon choices and try an unusual one.",
  'Action-creativity-10': "Replay a clip: \"What could I have done more creatively?\".",
  'Action-creativity-11': "Ask the squad: \"What creative play should we try next?\".",
  'Action-creativity-12': "Try a creative jump in a practice mode before the match.",
  'Action-creativity-13': "Practice a creative move in training daily for a week.",
  'Action-creativity-14': "Watch professional trick-shot videos for inspiration.",
  'Action-creativity-15': "Create a creative playbook for the squad to use.",
  'Action-creativity-16': "Lead a team that focuses on style points over winning.",

  // Creativity - RPG
  'RPG-creativity-1': "Imagine a world where the sun never rises.",
  'RPG-creativity-2': "Describe your dark-world concept to the party.",
  'RPG-creativity-3': "Write a short lore entry about your imagined world.",
  'RPG-creativity-4': "Find a creative way to reach a high ledge without flying.",
  'RPG-creativity-5': "Create a more creative way to decorate your character's gear.",
  'RPG-creativity-6': "Combine two different magic spells to see the effect.",
  'RPG-creativity-7': "Find a story loophole that allows for a new choice.",
  'RPG-creativity-8': "Set criteria for an immersive character backstory.",
  'RPG-creativity-9': "Challenge the standard heroic choices in the story.",
  'RPG-creativity-10': "Review your character stats: \"Is this too predictable?\".",
  'RPG-creativity-11': "Consult lore experts: \"Does this backstory fit the world?\".",
  'RPG-creativity-12': "Test a new gear combo on a weak mob for five minutes.",
  'RPG-creativity-13': "Develop a character's personality slowly over a campaign.",
  'RPG-creativity-14': "Read mythology to find new names or themes for a character.",
  'RPG-creativity-15': "Share a character creation template for the party.",
  'RPG-creativity-16': "Run a session where roleplay and story are the priorities.",

  // Creativity - Strategy
  'Strategy-creativity-1': "Imagine a civilisation that lives entirely underwater.",
  'Strategy-creativity-2': "Share your underwater city concept with a teammate.",
  'Strategy-creativity-3': "Use map markers to draw the layout of the city.",
  'Strategy-creativity-4': "Devise a creative way to gain resources without war.",
  'Strategy-creativity-5': "Suggest a creative way to improve city happiness scores.",
  'Strategy-creativity-6': "Combine two different tech paths to unlock a new unit.",
  'Strategy-creativity-7': "Identify a diplomatic gap to create a new trade route.",
  'Strategy-creativity-8': "Define the goals for a non-standard victory path.",
  'Strategy-creativity-9': "Question if expansion is always the best way to win.",
  'Strategy-creativity-10': "Critically review your trade deals: \"Is this too safe?\".",
  'Strategy-creativity-11': "Ask teammates: \"What is a wild way to win this match?\".",
  'Strategy-creativity-12': "Test a new research rush for ten turns to see the result.",
  'Strategy-creativity-13': "Allow a long-term strategy to develop over 50+ turns.",
  'Strategy-creativity-14': "Study historical battles to find a new strategic concept.",
  'Strategy-creativity-15': "Provide a mod or map script to change game rules.",
  'Strategy-creativity-16': "Host a tournament with wildcard rules to force creativity.",

  // Adapting - Sandbox
  'Sandbox-adapting-1': "Verbally identify your emotion when a build goes wrong.",
  'Sandbox-adapting-2': "Identify the mentor's reaction when you show them a completed build.",
  'Sandbox-adapting-3': "Continue working on a complex build even when a part of it breaks.",
  'Sandbox-adapting-4': "Take a breath and stay calm when a \"hazard\" damages your work.",
  'Sandbox-adapting-5': "Analyse why a structural build failed and try a different method.",
  'Sandbox-adapting-6': "Share your materials with a peer whose project has been damaged.",
  'Sandbox-adapting-7': "Tell a teammate \"Great effort\" after they struggle with a difficult build.",
  'Sandbox-adapting-8': "Take a water break or a stretch after completing a difficult build phase.",
  'Sandbox-adapting-9': "Break a city build into small, daily tasks to avoid feeling overwhelmed.",
  'Sandbox-adapting-10': "Try out a completely new building style you have never used before.",
  'Sandbox-adapting-11': "Treat an accidental fire or break as a chance to redesign the build.",
  'Sandbox-adapting-12': "Help a peer see that a mistake in their build actually looks unique.",
  'Sandbox-adapting-13': "Pivot your build style because the team ran out of a specific block.",
  'Sandbox-adapting-14': "Weigh the risk of using explosives near a build versus time gained.",
  'Sandbox-adapting-15': "Set up a backup of the server before starting a massive, risky project.",
  'Sandbox-adapting-16': "Use a new game update or mechanic to create a one-of-a-kind build.",

  // Adapting - Survival
  'Survival-adapting-1': "State how you feel when a specific survival resource is missing.",
  'Survival-adapting-2': "Recognise when a teammate is feeling stressed by a hostile environment.",
  'Survival-adapting-3': "Persist in gathering wood for a fire despite repeated environmental setbacks.",
  'Survival-adapting-4': "Respond calmly when you lose your inventory in a dangerous area.",
  'Survival-adapting-5': "Identify the specific mistake that led to a \"game over\" (e.g. lack of food).",
  'Survival-adapting-6': "Assist a teammate in recovering lost items from a hazardous zone.",
  'Survival-adapting-7': "Use the headset to tell the group \"We can get through this night!\".",
  'Survival-adapting-8': "Step away from the screen for two minutes if the pressure is high.",
  'Survival-adapting-9': "Focus on food for one day and building the next to avoid burnout.",
  'Survival-adapting-10': "Purposefully enter a harder environment to learn new survival mechanics.",
  'Survival-adapting-11': "Find a better resource spot because the original was blocked by enemies.",
  'Survival-adapting-12': "Point out a new resource opportunity to a teammate after a base is lost.",
  'Survival-adapting-13': "Change the base location because the original site is too dangerous.",
  'Survival-adapting-14': "Decide if exploring a cave at night is worth the risk for rare loot.",
  'Survival-adapting-15': "Carry extra potions and a respawn point when venturing into the wild.",
  'Survival-adapting-16': "Scale up production instantly when you find a mega-vein of resources.",

  // Adapting - Action
  'Action-adapting-1': "Identify your emotional state after an unexpected defeat.",
  'Action-adapting-2': "State how a teammate sounds during a high-pressure push.",
  'Action-adapting-3': "Stay in the match and keep playing after your primary gear is lost.",
  'Action-adapting-4': "Keep your voice steady and helpful after a failed tactical rotation.",
  'Action-adapting-5': "Review a clip to see why an engagement was lost and what to do next.",
  'Action-adapting-6': "Provide cover fire or items for a teammate who is pinned down.",
  'Action-adapting-7': "Encourage a teammate to stay in the game after they are eliminated early.",
  'Action-adapting-8': "Use a specific breathing technique before starting a new round.",
  'Action-adapting-9': "Only track one tactical objective at a time to keep your focus clear.",
  'Action-adapting-10': "Practice a specific advanced movement technique in a training area.",
  'Action-adapting-11': "Use a loss to test out a different, non-standard weapon or tactic.",
  'Action-adapting-12': "Show a teammate a new tactic because their old one was nerfed.",
  'Action-adapting-13': "Switch your character's loadout mid-match to counter a specific opponent.",
  'Action-adapting-14': "Analyse if a high-ground push is worth the risk of being spotted.",
  'Action-adapting-15': "Play defensively and stay near cover when your health or shields are low.",
  'Action-adapting-16': "Launch a surprise attack when you spot an opponent is distracted.",

  // Adapting - RPG
  'RPG-adapting-1': "Express your feeling when a story character makes a decision you dislike.",
  'RPG-adapting-2': "Identify the emotional tone of an NPC based on their dialogue or stance.",
  'RPG-adapting-3': "Keep trying to find the path to a quest objective after getting lost.",
  'RPG-adapting-4': "Accept a \"Quest Failed\" screen without external signs of distress.",
  'RPG-adapting-5': "Reflect on why a boss fight was unsuccessful and adjust your gear.",
  'RPG-adapting-6': "Offer a specific tip to a peer struggling with a complex puzzle mechanic.",
  'RPG-adapting-7': "Offer words of encouragement to the party after a difficult dungeon.",
  'RPG-adapting-8': "Identify when you are getting \"tilted\" and agree to switch tasks for 5 mins.",
  'RPG-adapting-9': "Focus on one quest branch at a time rather than cluttering the quest log.",
  'RPG-adapting-10': "Attempt a challenge run using only basic gear to improve your skill.",
  'RPG-adapting-11': "Use a failed quest line to explore a part of the map you missed.",
  'RPG-adapting-12': "Mentor a peer on how a bad story outcome opens up a new quest.",
  'RPG-adapting-13': "Change your character's stats to bypass a specific boss resistance.",
  'RPG-adapting-14': "Evaluate the risk of a moral choice in the story against the reward.",
  'RPG-adapting-15': "Use save points or specific gear to mitigate the danger of a boss.",
  'RPG-adapting-16': "Use an obscure story path to gain a unique, powerful item.",

  // Adapting - Strategy
  'Strategy-adapting-1': "State your feeling when an opponent makes a move that blocks yours.",
  'Strategy-adapting-2': "Identify the mood of an opponent through their chat or playstyle.",
  'Strategy-adapting-3': "Continue with your turn even after a surprise attack from a neutral faction.",
  'Strategy-adapting-4': "Stay calm and professional when an alliance is unexpectedly broken.",
  'Strategy-adapting-5': "Analyse why a specific research rush failed to give you the advantage.",
  'Strategy-adapting-6': "Send resources or gold to a teammate who is struggling with production.",
  'Strategy-adapting-7': "Motivate an ally to stick to the plan even if the map state looks poor.",
  'Strategy-adapting-8': "Use a routine (like checking the map) to ground yourself during a match.",
  'Strategy-adapting-9': "Manage production by focusing on one city or unit type at a time.",
  'Strategy-adapting-10': "Play as a new civilisation or faction to learn their unique strengths.",
  'Strategy-adapting-11': "Turn a lost territory into a chance to focus on a different victory path.",
  'Strategy-adapting-12': "Help an ally see how an opponent's move has left them vulnerable.",
  'Strategy-adapting-13': "Completely re-route your research path because an ally took the lead.",
  'Strategy-adapting-14': "Decide if a high-risk early war is worth the potential land gain.",
  'Strategy-adapting-15': "Divert gold into diplomacy to prevent a war while your army is weak.",
  'Strategy-adapting-16': "Take advantage of a market crash in the game economy to buy assets.",

  // Planning - Sandbox
  'Sandbox-planning-1': "Identify if a build project is too large to finish in a single session.",
  'Sandbox-planning-2': "Describe what the finished structure should look like before starting.",
  'Sandbox-planning-3': "Check that blocks are placed symmetrically and align with the floor plan.",
  'Sandbox-planning-4': "State whether you are better at exterior landscaping or interior design.",
  'Sandbox-planning-5': "Volunteer to lead a new, unfamiliar building style for the team.",
  'Sandbox-planning-6': "Set a goal to complete the foundations and walls by a set time.",
  'Sandbox-planning-7': "Discuss the order of operations (e.g. floor, then walls) before building.",
  'Sandbox-planning-8': "Decide whether to gather more materials or start building the frame first.",
  'Sandbox-planning-9': "Calculate the total number of blocks needed and gather them all first.",
  'Sandbox-planning-10': "Ask the mentor or a peer to assist with a specific, complex build part.",
  'Sandbox-planning-11': "Identify a new building technique you need to learn for a project.",
  'Sandbox-planning-12': "Break a large project into small stages with a target time for each.",
  'Sandbox-planning-13': "Ask the mentor for two different ways to improve the build's aesthetic.",
  'Sandbox-planning-14': "Use in-game signs or a blueprint to coordinate a group build.",
  'Sandbox-planning-15': "Review the build's block count to see if it fits the original dimensions.",
  'Sandbox-planning-16': "Redesign a structure mid-build to better fit the evolving terrain.",

  // Planning - Survival
  'Survival-planning-1': "Recognise when an area has enemies that are too high-level for your gear.",
  'Survival-planning-2': "Set a target for how many resources are needed to feel secure for the night.",
  'Survival-planning-3': "Organise the base storage carefully so vital items are easy to find.",
  'Survival-planning-4': "Identify if you are more effective at gathering or base defence.",
  'Survival-planning-5': "Proactively enter a new environment or dangerous area for the first time.",
  'Survival-planning-6': "Set a goal to reach a specific landmark or coordinate on the map.",
  'Survival-planning-7': "Map out a safe travel route to a distant resource location.",
  'Survival-planning-8': "Rank inventory items by must-have versus nice-to-have before a trek.",
  'Survival-planning-9': "Spend time specifically grinding for the materials needed to craft gear.",
  'Survival-planning-10': "Assign a task to a teammate (e.g. \"You hunt food while I gather wood\").",
  'Survival-planning-11': "Practice dodging or parrying in a safe area to prepare for a boss.",
  'Survival-planning-12': "Set a target to gather a specific stack of resources within ten minutes.",
  'Survival-planning-13': "Consult a community guide to see alternative ways to survive a biome.",
  'Survival-planning-14': "Coordinate a base expansion using a shared list of roles and duties.",
  'Survival-planning-15': "Analyse damage taken data to decide if a base needs more defence.",
  'Survival-planning-16': "Adjust the base's location and defence on the fly as new threats appear.",

  // Planning - Action
  'Action-planning-1': "Identify when a specific encounter requires more health or shields.",
  'Action-planning-2': "Define what a successful match looks like (e.g. reaching the top 10).",
  'Action-planning-3': "Double-check your ammunition and health supplies before moving out.",
  'Action-planning-4': "State whether you are better at scouting or close-quarters combat.",
  'Action-planning-5': "Attempt a new tactical move or weapon combo with a positive mindset.",
  'Action-planning-6': "Set a goal to achieve a specific number of eliminations or assists.",
  'Action-planning-7': "Plan a rotation route that keeps the team inside the safe zone.",
  'Action-planning-8': "Choose which enemy to target first based on the immediate threat level.",
  'Action-planning-9': "Ensure the whole squad has enough health kits before starting a fight.",
  'Action-planning-10': "Coordinate with the squad to ensure everyone is watching a different direction.",
  'Action-planning-11': "Plan to spend a match focusing purely on aiming or movement.",
  'Action-planning-12': "Define a target score or placement to achieve during the session.",
  'Action-planning-13': "Ask the squad for feedback on your call-out style during the match.",
  'Action-planning-14': "Use a map drawing tool to coordinate a multi-stage team rotation.",
  'Action-planning-15': "Review match stats to identify where the team's strategy was weakest.",
  'Action-planning-16': "Change the squad's rotation strategy mid-match based on enemy moves.",

  // Planning - RPG
  'RPG-planning-1': "Recognise when a boss or area requires a higher character level.",
  'RPG-planning-2': "State what a successful character build looks like for this session.",
  'RPG-planning-3': "Read quest dialogue carefully to ensure no clues are missed.",
  'RPG-planning-4': "Identify which character class or playstyle best fits your natural skills.",
  'RPG-planning-5': "Take on a complex multi-part quest without hesitation.",
  'RPG-planning-6': "Set a goal to reach the next level or unlock a specific ability.",
  'RPG-planning-7': "Identify the specific sub-quests needed to unlock a final objective.",
  'RPG-planning-8': "Decide which quest to complete first based on the reward provided.",
  'RPG-planning-9': "Earn the specific amount of gold required to purchase a vital item.",
  'RPG-planning-10': "Form a party with other players to take on a high-level dungeon.",
  'RPG-planning-11': "Choose specific character stats to level up for a future objective.",
  'RPG-planning-12': "Create a checklist of story items needed to finish the current arc.",
  'RPG-planning-13': "Seek advice from other players on the best gear for a specific boss.",
  'RPG-planning-14': "Follow a walkthrough or checklist to track 100% quest completion.",
  'RPG-planning-15': "Evaluate your character's damage output and re-allocate points if needed.",
  'RPG-planning-16': "Respec or change gear during a quest to counter a surprise boss move.",

  // Planning - Strategy
  'Strategy-planning-1': "Identify if an opponent's army is too large to engage safely.",
  'Strategy-planning-2': "Define the primary win condition you are aiming for in this match.",
  'Strategy-planning-3': "Check the map and unit positions thoroughly before ending your turn.",
  'Strategy-planning-4': "State which victory path (e.g. Science or Culture) you find easiest.",
  'Strategy-planning-5': "Propose a bold new strategic opening to the group.",
  'Strategy-planning-6': "Set a goal to settle one new city or research one specific technology.",
  'Strategy-planning-7': "Outline the sequence of buildings needed to unlock a specific unit.",
  'Strategy-planning-8': "Prioritise which city needs a new building most urgently.",
  'Strategy-planning-9': "Trade with an ally to secure a resource needed for city growth.",
  'Strategy-planning-10': "Form a research or military alliance with another player to reach a goal.",
  'Strategy-planning-11': "Plan which tech tree path to follow to unlock a specific playstyle.",
  'Strategy-planning-12': "Set a turn limit target to achieve a specific diplomatic or military goal.",
  'Strategy-planning-13': "Ask an ally for their perspective on the current map balance.",
  'Strategy-planning-14': "Use a tech calculator to plan a long-term victory path.",
  'Strategy-planning-15': "Use the victory screen metrics to see which city was most productive.",
  'Strategy-planning-16': "Adapt your entire victory path mid-game to respond to an opponent's lead.",

  // Leadership - Sandbox
  'Sandbox-leadership-1': "Verbally state how you feel about a shared building project.",
  'Sandbox-leadership-2': "Identify if a peer seems frustrated with a complex build part.",
  'Sandbox-leadership-3': "Explain why a specific design choice makes you feel excited or unsure.",
  'Sandbox-leadership-4': "Assign building roles fairly (e.g. \"I'll dig the hole, you gather the stone\").",
  'Sandbox-leadership-5': "Ensure everyone in the build team has the blocks and tools they need.",
  'Sandbox-leadership-6': "Show a less experienced builder a specific trick or \"building hack\".",
  'Sandbox-leadership-7': "Notice when a peer is becoming upset by accidental damage to a build.",
  'Sandbox-leadership-8': "Remind the team of the \"vision\" when a large build feels like too much work.",
  'Sandbox-leadership-9': "Recognise if you are better at \"Vision Setting\" or \"Task Management\".",
  'Sandbox-leadership-10': "Identify which peer is the best at \"fine detail\" work in a build.",
  'Sandbox-leadership-11': "Pitch a new \"Mega-Build\" in a way that gets the whole server excited.",
  'Sandbox-leadership-12': "Give a peer two specific \"tips\" on how to improve their building style.",
  'Sandbox-leadership-13': "Facilitate a group vote to decide the theme of a new shared village.",
  'Sandbox-leadership-14': "Create a multi-stage \"Development Plan\" for a massive shared world.",
  'Sandbox-leadership-15': "Review a group build to see if the team worked efficiently under you.",
  'Sandbox-leadership-16': "Switch from \"Directing\" to \"Supporting\" as the builders gain confidence.",

  // Leadership - Survival
  'Survival-leadership-1': "Identify your emotion when the group's base is compromised.",
  'Survival-leadership-2': "Recognise when a teammate is feeling overwhelmed by survival pressure.",
  'Survival-leadership-3': "Describe how a proposed base location affects your sense of security.",
  'Survival-leadership-4': "Divide survival duties (e.g. \"One person hunts, one person crafts\").",
  'Survival-leadership-5': "Manage the shared chest to ensure food and fuel are evenly distributed.",
  'Survival-leadership-6': "Mentor a peer on how to survive a specific biome or enemy type.",
  'Survival-leadership-7': "Recognise when the group is getting demotivated by a difficult grind.",
  'Survival-leadership-8': "Boost group morale after the base is destroyed by encouraging a rebuild.",
  'Survival-leadership-9': "Identify if you lead better by \"Doing\" or by \"Directing\" during survival.",
  'Survival-leadership-10': "Recognise which teammate is the most efficient at resource gathering.",
  'Survival-leadership-11': "Motivate the group to take on a high-risk exploration for a rare reward.",
  'Survival-leadership-12': "Provide constructive advice on a teammate's survival gear choices.",
  'Survival-leadership-13': "Mediate a debate between teammates about where to move the base.",
  'Survival-leadership-14': "Design a \"Survival Roadmap\" for the team to reach the late-game.",
  'Survival-leadership-15': "Analyse a base defence to see if your task delegation was effective.",
  'Survival-leadership-16': "Change your leadership style from \"Risk-Taker\" to \"Cautious\" as health drops.",

  // Leadership - Action
  'Action-leadership-1': "State your feeling after a successful or failed team engagement.",
  'Action-leadership-2': "Sense if a teammate is feeling \"tilted\" or stressed during a match.",
  'Action-leadership-3': "Explain your feelings about a risky tactical move before the team commits.",
  'Action-leadership-4': "Assign squad roles (e.g. \"One person scouts, two people assault\").",
  'Action-leadership-5': "Call out when the squad needs to stop and restock ammo or health.",
  'Action-leadership-6': "Coach a teammate on a specific movement or aiming technique.",
  'Action-leadership-7': "Spot when a teammate is becoming angry or quiet after a defeat.",
  'Action-leadership-8': "Keep the squad's spirits up with positive call-outs during a tough match.",
  'Action-leadership-9': "State whether you are a \"Tactical Leader\" or a \"Morale Booster\".",
  'Action-leadership-10': "Spot which squad member has the best \"game sense\" or map awareness.",
  'Action-leadership-11': "Use an inspiring \"pre-match\" brief to build squad confidence.",
  'Action-leadership-12': "Offer a \"Post-Match\" tip to a teammate on their positioning or aim.",
  'Action-leadership-13': "Lead a squad \"debrief\" to agree on the next round's landing spot.",
  'Action-leadership-14': "Create a \"Tournament Strategy\" with specific roles for every teammate.",
  'Action-leadership-15': "Review a match recording to see if your call-outs were clear and useful.",
  'Action-leadership-16': "Adapt your \"Command Style\" mid-match to suit the squad's stress levels.",

  // Leadership - RPG
  'RPG-leadership-1': "Express how you feel about the party's current quest progress.",
  'RPG-leadership-2': "Identify the emotional state of a party member during a story choice.",
  'RPG-leadership-3': "Share your emotional reaction to a plot twist with the group.",
  'RPG-leadership-4': "Allocate quest roles based on character class or current gear.",
  'RPG-leadership-5': "Manage the party's gold to ensure everyone can afford necessary upgrades.",
  'RPG-leadership-6': "Explain a complex game mechanic or lore point to a new party member.",
  'RPG-leadership-7': "Identify when the party is conflicted about a sensitive story decision.",
  'RPG-leadership-8': "Encourage the party to stick together after a major in-game setback.",
  'RPG-leadership-9': "Identify your strength in mediating story disputes within the party.",
  'RPG-leadership-10': "Identify which party member is the most effective at solving puzzles.",
  'RPG-leadership-11': "Use \"In-Character\" speeches to motivate the party before a boss.",
  'RPG-leadership-12': "Give feedback to a party member on their role-playing or combat choices.",
  'RPG-leadership-13': "Manage a discussion on which \"Faction\" the party should support.",
  'RPG-leadership-14': "Develop a \"Campaign Plan\" that guides the party through all main quests.",
  'RPG-leadership-15': "Evaluate if your party management led to a successful quest outcome.",
  'RPG-leadership-16': "Pivot your role within the party based on the emotional needs of peers.",

  // Leadership - Strategy
  'Strategy-leadership-1': "State your feeling regarding the current state of a team alliance.",
  'Strategy-leadership-2': "Recognise when an ally is feeling unconfident about a strategic move.",
  'Strategy-leadership-3': "Explain why a specific treaty or trade makes you feel uneasy.",
  'Strategy-leadership-4': "Divide map sectors between allies to ensure equal resource coverage.",
  'Strategy-leadership-5': "Distribute surplus resources to an ally who is falling behind in production.",
  'Strategy-leadership-6': "Guide an ally through a complex diplomatic or economic system.",
  'Strategy-leadership-7': "Notice when an ally is becoming anxious about an enemy's military build-up.",
  'Strategy-leadership-8': "Reassure an ally that the long-term strategy is working despite local losses.",
  'Strategy-leadership-9': "Recognise if your leadership style is \"Aggressive\" or \"Diplomatic\".",
  'Strategy-leadership-10': "Recognise which ally is the best at managing the team's shared economy.",
  'Strategy-leadership-11': "Persuade an alliance to commit to a bold, game-winning strategy.",
  'Strategy-leadership-12': "Provide an ally with data-driven feedback on their resource management.",
  'Strategy-leadership-13': "Facilitate an alliance meeting to agree on a shared victory condition.",
  'Strategy-leadership-14': "Design a \"Global Strategy\" for an alliance to control the map.",
  'Strategy-leadership-15': "Review an alliance's progress to see if your strategic lead was correct.",
  'Strategy-leadership-16': "Adapt your \"Diplomatic Lead\" based on the shifting loyalties of allies.",

  // Teamwork - Sandbox
  'Sandbox-teamwork-1': "Work on the same build site as a peer without interfering with their work.",
  'Sandbox-teamwork-2': "Adhere to the \"build height\" or \"material\" rules agreed for the area.",
  'Sandbox-teamwork-3': "Complete your assigned section of a build (e.g. the roof) as promised.",
  'Sandbox-teamwork-4': "Fix any accidental damage you cause to a shared build immediately.",
  'Sandbox-teamwork-5': "Offer blocks to a peer who has run out of materials mid-build.",
  'Sandbox-teamwork-6': "Ask a peer to help you finish a large section of a build.",
  'Sandbox-teamwork-7': "Acknowledge that a peer’s design idea is better for the project.",
  'Sandbox-teamwork-8': "Incorporate a peer’s suggestion into your part of the build.",
  'Sandbox-teamwork-9': "List all the different roles needed for a \"Mega-Build\" project.",
  'Sandbox-teamwork-10': "Check in with builders to see who is on track and who needs help.",
  'Sandbox-teamwork-11': "Spend a session doing \"boring\" prep work to help the team’s big build.",
  'Sandbox-teamwork-12': "Review the build progress against the original \"blueprint\" or vision.",
  'Sandbox-teamwork-13': "Mediate a dispute between two builders over a shared space.",
  'Sandbox-teamwork-14': "De-escalate a situation where a build was accidentally \"griefed\".",
  'Sandbox-teamwork-15': "Lead a discussion on how the team’s communication improved the build.",
  'Sandbox-teamwork-16': "Create a new \"Communication Protocol\" for future group builds.",

  // Teamwork - Survival
  'Survival-teamwork-1': "Stay near the group while gathering basic resources.",
  'Survival-teamwork-2': "Follow the group’s rule on \"communal chest\" usage and sharing.",
  'Survival-teamwork-3': "Keep the base fire lit or the \"hunger\" bar filled for the group.",
  'Survival-teamwork-4': "Admit when you forgot to restock a vital resource and work to fix it.",
  'Survival-teamwork-5': "Give your spare food or tools to a teammate who is struggling.",
  'Survival-teamwork-6': "Request assistance from the group to recover your lost inventory.",
  'Survival-teamwork-7': "Try a teammate's suggested survival method even if it’s new to you.",
  'Survival-teamwork-8': "Publicly thank a teammate for their efficient resource gathering.",
  'Survival-teamwork-9': "Identify all the survival duties (scouting, cooking, guarding).",
  'Survival-teamwork-10': "Review the shared inventory to see which survival tasks are falling behind.",
  'Survival-teamwork-11': "Sacrifice your personal gear to ensure the group base survives a raid.",
  'Survival-teamwork-12': "Analyse a \"Base Wipe\" to see which team roles failed to connect.",
  'Survival-teamwork-13': "Negotiate a fair split of rare resources after a dangerous trek.",
  'Survival-teamwork-14': "Address \"blame\" after a survival loss and refocus the team on a rebuild.",
  'Survival-teamwork-15': "Analyse if the group’s \"division of labour\" was efficient for survival.",
  'Survival-teamwork-16': "Design a \"Base Charter\" that improves how the group shares resources.",

  // Teamwork - Action
  'Action-teamwork-1': "Stay with the squad during the initial phase of a match.",
  'Action-teamwork-2': "Follow the squad’s \"no-fire\" or \"stealth\" orders until the signal.",
  'Action-teamwork-3': "Hold your assigned position or \"lane\" during a defensive hold.",
  'Action-teamwork-4': "Take accountability for a missed call-out or a tactical error.",
  'Action-teamwork-5': "Drop ammunition or health kits for a squad member in need.",
  'Action-teamwork-6': "Call for backup or \"support fire\" when you are outnumbered.",
  'Action-teamwork-7': "Agree to use a teammate’s tactical route over your own.",
  'Action-teamwork-8': "Highlight a squad member’s great \"save\" or \"play\" to the group.",
  'Action-teamwork-9': "Map out the different squad roles (sniper, medic, fragger).",
  'Action-teamwork-10': "Monitor the squad's status (health/ammo) during a long match.",
  'Action-teamwork-11': "Play a \"support\" role purely to help a teammate get the win.",
  'Action-teamwork-12': "Review match stats to see if the squad achieved its \"shared\" goals.",
  'Action-teamwork-13': "Resolve a disagreement over which landing spot is best for the squad.",
  'Action-teamwork-14': "Calm the squad down after a frustrating or \"unfair\" match defeat.",
  'Action-teamwork-15': "Review a match to see if the squad’s \"synergy\" led to the outcome.",
  'Action-teamwork-16': "Lead a \"Team-Building\" match focused on trust and coordination.",

  // Teamwork - RPG
  'RPG-teamwork-1': "Follow the party leader to the first quest objective.",
  'RPG-teamwork-2': "Abide by the party’s agreement on how to divide loot.",
  'RPG-teamwork-3': "Complete your specific role in a combat encounter (e.g. healing).",
  'RPG-teamwork-4': "Admit when you triggered a trap or enemy and help the party recover.",
  'RPG-teamwork-5': "Use a protective ability or item to save a party member.",
  'RPG-teamwork-6': "Ask the party for help with a puzzle or a high-level enemy.",
  'RPG-teamwork-7': "Support a party member’s choice of quest or dialogue path.",
  'RPG-teamwork-8': "Support a peer's roleplay choice by reacting \"in-character\".",
  'RPG-teamwork-9': "Identify the specific roles needed to bypass a complex dungeon.",
  'RPG-teamwork-10': "Check the party’s progress against the quest log requirements.",
  'RPG-teamwork-11': "Choose a character \"buff\" that helps the party more than yourself.",
  'RPG-teamwork-12': "Evaluate if the party’s current gear is sufficient for the final quest.",
  'RPG-teamwork-13': "Mediate a conflict between party members over a story choice.",
  'RPG-teamwork-14': "Manage tensions within the party during high-pressure boss fights.",
  'RPG-teamwork-15': "Evaluate how well the party supported each other during a quest.",
  'RPG-teamwork-16': "Facilitate a party meeting to improve role-playing and support.",

  // Teamwork - Strategy
  'Strategy-teamwork-1': "Move your units in coordination with an ally’s opening move.",
  'Strategy-teamwork-2': "Respect the \"borders\" and \"territories\" agreed upon with an ally.",
  'Strategy-teamwork-3': "Deliver a promised resource or unit to an ally on time.",
  'Strategy-teamwork-4': "Own a strategic mistake that cost the alliance a territory.",
  'Strategy-teamwork-5': "Send gold or units to an ally who is under heavy attack.",
  'Strategy-teamwork-6': "Request a resource trade from an ally to finish a vital project.",
  'Strategy-teamwork-7': "Vote in favour of an ally's strategic plan during a meeting.",
  'Strategy-teamwork-8': "Praise an ally's clever move during a joint military operation.",
  'Strategy-teamwork-9': "List the different roles within an alliance (banker, general, spy).",
  'Strategy-teamwork-10': "Review an alliance's production stats to see if targets are being met.",
  'Strategy-teamwork-11': "Transfer your best territory to an ally to help the alliance win.",
  'Strategy-teamwork-12': "Review the map to see if the alliance is on track for victory.",
  'Strategy-teamwork-13': "Negotiate a complex multi-way trade to satisfy all allies.",
  'Strategy-teamwork-14': "Address a \"betrayal\" or mistrust within an alliance professionally.",
  'Strategy-teamwork-15': "Review an alliance’s coordination during a major map event.",
  'Strategy-teamwork-16': "Design a new \"Alliance Structure\" to ensure better long-term cooperation.",
};

export const getCatalystTask = (genre: Genre, skillId: string, step: number): string => {
  const key = `${genre}-${skillId}-${step}`;
  if (CATALYST_TASKS[key]) return CATALYST_TASKS[key];
  
  // Fallback generator for demo purposes
  const skill = SKILLS.find(s => s.id === skillId)?.name || 'this skill';
  return `[Custom Task] In a ${genre} game, practice ${skill} at Step ${step} by setting a specific goal related to the session's objective and reflecting on your progress.`;
};
